[profile.default]
solc-version = "0.8.20"
src = 'contracts'
out = 'output/out'
libs = ['lib']
test = 'tests'
cache_path  = 'output/cache_forge'
optimizer = true
optimizer-runs = 10_000_000

remappings = [
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
]

[fuzz]
runs = 1000

[rpc_endpoints]
base_sepolia = "${RPC_URL}"

[etherscan]
base_sepolia = { key = "${API_KEY}", chain = "84532", url = "${RPC_URL}" }