name: Build & Test

on:
  push:
    branches: [$default-branch]
  pull_request:
    branches:
      - "**"
env:
  COIN_MARKET_CAP: ${{ secrets.COIN_MARKET_CAP }}
  MAIN_NET_FORK_API_KEY: ${{ secrets.MAIN_NET_FORK_API_KEY }}
  GOERLI_API_KEY: ${{ secrets.GOERLI_API_KEY }}
  GOERLI_OWNER_PRIVATE_KEY: ${{ secrets.GOERLI_OWNER_PRIVATE_KEY }}
  GOERLI_ADMIN_PRIVATE_KEY: ${{ secrets.GOERLI_ADMIN_PRIVATE_KEY }}
  GOERLI_USER_PRIVATE_KEY: ${{ secrets.GOERLI_USER_PRIVATE_KEY }}
  GOERLI_BORROWER_PRIVATE_KEY: ${{ secrets.GOERLI_BORROWER_PRIVATE_KEY }}
  CELO_API_KEY: ${{ secrets.CELO_API_KEY }}
  CELO_OWNER_PRIVATE_KEY: ${{ secrets.CELO_OWNER_PRIVATE_KEY }}
  CELO_ADMIN_PRIVATE_KEY: ${{ secrets.CELO_ADMIN_PRIVATE_KEY }}
  CELO_USER_PRIVATE_KEY: ${{ secrets.CELO_USER_PRIVATE_KEY }}
  CELO_BORROWER_PRIVATE_KEY: ${{ secrets.CELO_BORROWER_PRIVATE_KEY }}

defaults:
  run:
    working-directory: packages/helios-contracts
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
        
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
          
      - name: Yarn install
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install

      - name: Yarn compile        
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: compile 
          
      - name: Hardhat tests
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: test

      - name: Forge tests
        run: forge test -vvv --no-match-contract "PoolFactoryTest|HeliosGlobalsTest"
        
      - name: Yarn Generate abi
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: export
          CELO_BORROWER_PRIVATE_KEY: ${{ secrets.CELO_BORROWER_PRIVATE_KEY }} 


