name: Build & Test

on:
  push:
    branches: [$default-branch]
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install just
        uses: extractions/setup-just@v1

      - name: Forge tests
        run: just test-all
        
