name: Build & Test

on:
  push:
    branches: [$default-branch]
  pull_request:
    branches:
      - "**"
      
defaults:
  run:
    working-directory: packages/helios-contracts
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: compile
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: test
