name: Build & Test

on:
  push:
    branches: [$default-branch]
  pull_request:
    branches:
      - "**"
      
defaults:
  run:
    working-directory: packages/helios-contracts
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Yarn install
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install

      - name: Yarn compile        
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: compile
        env:
          COIN_MARKET_CAP: ${{ secrets.COIN_MARKET_CAP }}
          MAIN_NET_FORK_API_KEY: ${{ secrets.MAIN_NET_FORK_API_KEY }}
          GOERLI_API_KEY: ${{ secrets.GOERLI_API_KEY }}
          GOERLI_OWNER_PRIVATE_KEY: ${{ secrets.GOERLI_OWNER_PRIVATE_KEY }}
          GOERLI_ADMIN_PRIVATE_KEY: ${{ secrets.GOERLI_ADMIN_PRIVATE_KEY }}
          GOERLI_USER_PRIVATE_KEY: ${{ secrets.GOERLI_USER_PRIVATE_KEY }}
          
      - name: Yarn test
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: test
        env:
          COIN_MARKET_CAP: ${{ secrets.COIN_MARKET_CAP }}
          MAIN_NET_FORK_API_KEY: ${{ secrets.MAIN_NET_FORK_API_KEY }}
          GOERLI_API_KEY: ${{ secrets.GOERLI_API_KEY }}
          GOERLI_OWNER_PRIVATE_KEY: ${{ secrets.GOERLI_OWNER_PRIVATE_KEY }}
          GOERLI_ADMIN_PRIVATE_KEY: ${{ secrets.GOERLI_ADMIN_PRIVATE_KEY }}
          GOERLI_USER_PRIVATE_KEY: ${{ secrets.GOERLI_USER_PRIVATE_KEY }}


      - name: Yarn Generate abi
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: export
