name: Build & Test

on:
  push:
    branches: [$default-branch]
  pull_request:
    branches:
      - "**"
      
defaults:
  run:
    working-directory: packages/helios-contracts
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Yarn install
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install

      - name: Yarn compile        
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: compile
          
      - name: Yarn test
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: test

      - name: Yarn Generate abi
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: export
          
      - name: Pushes to helios-admin
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'abi'
          destination-github-username: 'traqel'
          destination-repository-name: 'groksmith/helios-admin'
          user-email: traqel@gmail.com
          target-branch: develop
